# Generated by Django 5.2.17 on 2026-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0050_filterpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Version'),
        ),
    ]
