# Generated by Django 5.2.17 on 2026-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0051_transaction_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='generated_by_action_execution_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Generated by rule action execution'),
        ),
    ]
