# Generated by Django 5.2.17 on 2026-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_transactionrule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrule',
            name='execution_mode',
            field=models.CharField(choices=[('atomic', 'Atomic'), ('isolated', 'Rule-level isolation')], default='atomic', help_text='Atomic rolls back every action if one fails. Rule-level isolation commits each action independently.', max_length=20, verbose_name='Execution mode'),
        ),
        migrations.AddField(
            model_name='transactionrule',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
    ]
