# Generated by Django 5.2.17 on 2026-10-05 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0019_transactionrule_execution_mode_and_more'),
        ('transactions', '0052_transaction_generated_by_action_execution_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.BigIntegerField(verbose_name='Transaction ID')),
                ('rule_ref', models.BigIntegerField(verbose_name='Rule ID')),
                ('event', models.CharField(choices=[('created', 'Transaction created'), ('updated', 'Transaction updated'), ('deleted', 'Transaction deleted')], max_length=20, verbose_name='Event')),
                ('transaction_version', models.PositiveBigIntegerField(verbose_name='Transaction version')),
                ('rule_version', models.PositiveBigIntegerField(verbose_name='Rule version')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('stale', 'Stale'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_executions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_executions', to='rules.transactionrule', verbose_name='Rule')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_executions', to='transactions.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Rule execution',
                'verbose_name_plural': 'Rule executions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RuleActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('edit_transaction', 'Edit transaction'), ('update_or_create_transaction', 'Update or create transaction')], max_length=40, verbose_name='Action type')),
                ('action_ref', models.BigIntegerField(verbose_name='Action ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rolled_back', 'Rolled back')], max_length=20, verbose_name='Status')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
                ('effects', models.JSONField(blank=True, default=list, verbose_name='Effects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_executions', to='rules.ruleexecution', verbose_name='Rule execution')),
            ],
            options={
                'verbose_name': 'Rule action execution',
                'verbose_name_plural': 'Rule action executions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['status'], name='rules_rulee_status_10e59a_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['transaction_ref', 'event'], name='rules_rulee_transac_332f43_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleexecution',
            constraint=models.UniqueConstraint(fields=('transaction_ref', 'event', 'transaction_version', 'rule_ref', 'rule_version'), name='rule_execution_unique_key'),
        ),
    ]
